name: Build, Push, and Update Docker Images

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Images
      env:
        DOCKER_REGISTRY: docker.io/chetanpatil@2003  # Replacchetanpatil2003 e with your Docker registry
        IMAGE_VERSION: 1.16.3  # Replace with your desired image version
      run: |
        cd samples/bookinfo
        src/build-services.sh ${{ env.IMAGE_VERSION }} ${{ env.DOCKER_REGISTRY }}
        # Push the images to Docker Hub
        docker push ${{ env.DOCKER_REGISTRY }}/examples-bookinfo-ratings-v2:${{ env.IMAGE_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY }}/examples-bookinfo-ratings-v2:latest

    - name: Update YAML Files
      env:
        IMAGE_VERSION: 1.16.3  # Replace with your desired image version
      run: |
        sed -i "s//${{ env.IMAGE_VERSION }}/g" platform/kube/bookinfo*.yaml

    

